name: Build Server Image

on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Install Guix
        uses: PromyLOPh/guix-install-action@v1
        with:
          channels: |-
            (list (channel
                    (name 'guix)
                    (url "https://git.savannah.gnu.org/git/guix.git")
                    (branch "master")
                    (commit
                      "8860e9db560c5d9e74277b608071fbb93579db4f")
                    (introduction
                      (make-channel-introduction
                        "9edb3f66fd807b096b48283debdcddccfea34bad"
                        (openpgp-fingerprint
                          "BBB0 2DDF 2CEA F6A8 0D1D  E643 A2A0 6DF2 A33A 54FA")))))

      - name: Build Image
        run: |
          image=$(guix system image --save-provenance server.scm)
          cp $image server.img
          export RELEASE_TAG=$(date +"%Y%m%d%H%M")
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: crafter-chat - ${{ env.RELEASE_TAG }}
          tag_name: v${{ env.RELEASE_TAG }}
          files: server.img
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: SystemCrafters/crafter-chat
